# This is a config for E2B sandbox template.
# You can use template ID (f9ffolm62plbj2hso51u) or template name (autopilot-dev) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("autopilot-dev") # Sync sandbox
# sandbox = await AsyncSandbox.create("autopilot-dev") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('autopilot-dev')

team_id = "f6e7d641-e017-474d-8a0f-0db283cfc8d1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "autopilot-dev"
template_id = "f9ffolm62plbj2hso51u"
